apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fmt-webserver
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: sample-app
      version: 0.1.3
      sourceRef:
        kind: HelmRepository
        name: fmt-helmrepo
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/mbaykara/sample-app
      tag: v0.2.2 # {"$imagepolicy": "flux-system:prod-instance:tag"}
    service:
      port: 8090
    env_map:
    - name: REGION
      value: "WEST CAPE"
